### ISSUE TITLE
Support for multi-dimensional grids

### ISSUE THREAD

**Issue by FoxNerdSaysMoo** [GrandMoff100/PyGrids#1]
## Feature Idea
Add support for a multi dimensional grid through MultiGrid, a wrapper of Grid:

`
class MultiGrid: `
`    def __init__(self, dims: tuple) `
`        self.grid = Grid() # Spawn in grids inside of grids somehow
`

**Comment by GrandMoff100** [comment]
Working on it.

**Comment by GrandMoff100** [comment]
Bare Functionality has been added, please check https://pypi.org/project/PyGrids/ for the newest version or ``pip install pygrids --upgrade``

**Comment by GrandMoff100** [comment]
Please let me know with any bugs, and/or enhancements you would like.
